global_url = "http://localhost:5000/"
localManagerUrl = "http://localhost:5001/"
hostUrl = "https://raw.githubusercontent.com/AuraMiddleware/aura-semantics/master/semantics/"
ontologyUrl = hostUrl + "ontologies/"
contextUrl = hostUrl + "contexts/"
