globalManagerUrl = "http://localhost:5000/"
localManagerUrl = "http://localhost:5001/"
hostUrl = "file:///home/vinicius/UFPE/TG/AuraMiddleware/semantics/"
ontologyUrl = hostUrl + "ontologies/"
contextUrl = hostUrl + "contexts/"